<?php
require_once __DIR__ . '/../config.php';

// Fallbacks si no definiste constantes:
$iniPath = defined('INI_PATH') ? INI_PATH : (__DIR__ . '/../config/default_messages.ini');

// Crear si no existe
if (!file_exists($iniPath)) {
    @mkdir(dirname($iniPath), 0777, true);
    file_put_contents($iniPath, "[MESSAGES]\nmessagecreate = Game created: {game_name}\nmessageplayer = {user} connected from {ip}\nmessagetoleave = {user} left the game\nmessagetoconnect = Connected to server {SERVIDOR}\n");
}

// Cargar INI
$config = new \stdClass();
$config->MESSAGES = [];
$ini = parse_ini_file($iniPath, true, INI_SCANNER_TYPED);
if (!is_array($ini)) $ini = [];
if (!isset($ini['MESSAGES'])) $ini['MESSAGES'] = [];
$config->MESSAGES = $ini['MESSAGES'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json');
    // inputs como messages[key] => value
    $messages = $_POST['messages'] ?? [];
    // reconstruir INI
    $out  = "; Auto-generated by panel\n[MESSAGES]\n";
    foreach ($messages as $k => $v) {
        $k = preg_replace('/[^a-zA-Z0-9_\-]/', '_', $k);
        $line = $k . " = " . str_replace(["\r","\n"], ['',' '], $v);
        $out .= $line . "\n";
    }
    file_put_contents($iniPath, $out);
    echo json_encode(['success'=>true, 'msg'=>'Mensajes guardados en default_messages.ini']);
    exit;
}
?>
<div class="container py-4">
  <h2 class="mb-3">Editar default_messages.ini</h2>
  <div id="msgIni" class="alert d-none"></div>

  <form id="formIni" class="bg-dark p-4 rounded text-light">
    <p class="text-white mb-3">
  Variables disponibles en plantillas (según evento):
  <code>{game_name}</code>, <code>{user}</code>, <code>{ip}</code>, <code>{SERVIDOR}</code>.
</p>
    <?php if (empty($config->MESSAGES)): ?>
      <div class="alert alert-warning">No hay claves en [MESSAGES].</div>
    <?php else: foreach ($config->MESSAGES as $key=>$val): ?>
      <div class="mb-3">
        <label class="form-label"><?= htmlspecialchars($key) ?></label>
        <input type="text" name="messages[<?= htmlspecialchars($key) ?>]" class="form-control bg-secondary text-light" value="<?= htmlspecialchars($val) ?>">
      </div>
    <?php endforeach; endif; ?>

    <hr>
    <h5>Agregar nueva clave</h5>
    <div class="row g-2">
      <div class="col-md-4">
        <input class="form-control bg-secondary text-light" id="newKey" placeholder="nueva_clave">
      </div>
      <div class="col-md-8">
        <input class="form-control bg-secondary text-light" id="newVal" placeholder="valor de la plantilla">
      </div>
    </div>
    <button type="button" id="addKey" class="btn btn-sm btn-outline-light mt-2">Añadir</button>

    <div class="mt-4">
      <button class="btn btn-primary">Guardar</button>
    </div>
  </form>
</div>

<script>
$(function(){
  $('#addKey').on('click', function(){
    const k = $('#newKey').val().trim();
    const v = $('#newVal').val();
    if(!k) return alert('Ingresa una clave');
    const safe = k.replace(/[^a-zA-Z0-9_\-]/g,'_');
    const group = $('<div class="mb-3">\
      <label class="form-label"></label>\
      <input type="text" class="form-control bg-secondary text-light" name="messages['+safe+']">\
    </div>');
    group.find('label').text(safe);
    group.find('input').val(v);
    $(group).insertBefore($('#formIni hr'));
    $('#newKey,#newVal').val('');
  });

  $('#formIni').on('submit', function(e){
    e.preventDefault();
    const data = $(this).serialize();
    $.post('pages/edit_messages.php', data, function(res){
      const box = $('#msgIni');
      box.removeClass('d-none alert-danger').addClass('alert alert-success').text(res.msg||'Guardado');
      setTimeout(()=>box.addClass('d-none'),3000);
    }, 'json').fail(()=>{
      $('#msgIni').removeClass('d-none alert-success').addClass('alert alert-danger').text('Error guardando');
    });
  });
});
</script>
